CREATE EXTERNAL TABLE Hospital_External
(PROVIDERID varchar(100),
HOSPITALNAME varchar(500),
ADDRESS varchar(500),
CITY varchar(500),
STATE varchar(100),
ZIPCODE varchar(25),
COUNTYNAME varchar(500),
PHONENUMBER varchar(100),
HOSPITALTYPE varchar(500),
HOSPITALOWNERSHIP varchar(500),
EMERGENCYSERVICES varchar(25))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare';

CREATE EXTERNAL TABLE Effective_Care_External
(PROVIDERID varchar(100),
HOSPITALNAME varchar(500),
ADDRESS varchar(500),
CITY varchar(500),
STATE varchar(100),
ZIPCODE varchar(25),
COUNTYNAME varchar(500),
PHONENUMBER varchar(100),
CONDITION varchar(500),
MEASUREID varchar(500),
MEASURENAME varchar(500),
SCORE varchar(500),
SAMPLE varchar(500),
FOOTNOTE varchar(500),
MEASURESTARTDATE varchar(100),
MEASUREENDDATE varchar(100))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare';

CREATE EXTERNAL TABLE Readmissions_External
(PROVIDERID varchar(100),
HOSPITALNAME varchar(500),
ADDRESS varchar(500),
CITY varchar(500),
STATE varchar(100),
ZIPCODE varchar(25),
COUNTYNAME varchar(500),
PHONENUMBER varchar(100),
MEASURENAME varchar(500),
MEASUREID varchar(500),
COMPAREDTONATIONAL varchar(500),
DENOMINATOR varchar(500),
SCORE varchar(500),
LOWERESTIMATE varchar(100),
HIGHERESTIMATE varchar(100),
FOOTNOTE varchar(500),
MEASURESTARTDATE varchar(100),
MEASUREENDDATE varchar(100))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare';

CREATE EXTERNAL TABLE Measure_Dates_External
(MEASURENAME varchar(500),
MEASUREID varchar(500),
MEASURESTARTQUARTER varchar(100),
MEASURESTARTDATE varchar(100),
MEASUREENDQUARTER varchar(100),
MEASUREENDDATE varchar(100))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare';

CREATE EXTERNAL TABLE Survey_Responses_External
(PROVIDERID varchar(100),
HOSPITALNAME varchar(500),
ADDRESS varchar(500),
CITY varchar(500),
STATE varchar(100),
ZIPCODE varchar(25),
COUNTYNAME varchar(500),
COMMNURSEACHVPTS varchar(500),
COMMNURSEIMPRVPTS varchar(500),
COMMNURSEDIMSCORE varchar(500),
COMMDOCACHVPTS varchar(500),
COMMDOCIMPRVPTS varchar(500),
COMMDOCDIMSCORE varchar(500),
RESPHOSPSTAFFACHVPTS varchar(500),
RESPHOSPSTAFFIMPRVPTS varchar(500),
RESPHOSPSTAFFDIMSCORE varchar(500),
PAINMGMTACHVPTS varchar(500),
PAINMGMTIMPRVPTS varchar(500),
PAINMGMTDIMSCORE varchar(500),
COMMMEDSACHVPTS varchar(500),
COMMMEDSIMPRVPTS varchar(500),
COMMMEDSDIMSCORE varchar(500),
CLEANQUIETHOSPENVACHVPTS varchar(500),
CLEANQUIETHOSPENVIMPRVPTS varchar(500),
CLEANQUIETHOSPENVDIMSCORE varchar(500),
DCHARGEINFOACHVPTS varchar(500),
DCHARGEINFOIMPRVPTS varchar(500),
DCHARGEINFODIMSCORE varchar(500),
OVERALLRATEHOSPACHVPTS varchar(500),
OVERALLRATEHOSPIMPRVPTS varchar(500),
OVERALLRATEHOSPDIMSCORE varchar(500),
HCAHPSBASESCORE varchar(500),
HCAHPSCONSSCORE varchar(500))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare';
